name: netflix
description: A new Flutter project.

publish_to: 'none'

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  bordered_text: ^2.0.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  freezed_annotation: 1.1.0
  get_it: ^7.2.0
  injectable: ^1.5.3
  json_annotation: ^4.4.0
  json_serializable: ^6.1.5
  lottie: ^1.3.0
  share_plus: ^4.0.3
  video_player: ^2.3.0

dev_dependencies:
  build_runner: ^2.1.8
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  injectable_generator: ^1.5.3

flutter:

  uses-material-design: true

  assets:
    - assets/images/
